### ISSUE TITLE
add parameter names for clarity

### ISSUE THREAD

**Issue by cjyetman** [vincentarelbundock/countrycode_joss#2]
Might make sense to name the parameters in the function call examples for clarity, e.g. `countrycode(c('DZA', 'USA'), origin = 'iso3c', destination = 'cowc')`

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode_joss/commit/a8d064ae621e8ae2df8613bb2e9119d76d8e5745
