### ISSUE TITLE
Ready for submission?

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode_joss#3]
I fixed the two issues raised by @cjyetman and included @NilsEnevoldsen author information.

Unless either of you has other suggestions, I'll submit to JOSS.

Waiting for your confirmation.

**Comment by cjyetman** [comment]
pretty sure "EuroStat" should be "Eurostat", but other than that, I give a 👍🏼

**Comment by NilsEnevoldsen** [comment]
Thanks. I'll review by end-of-day.

**Comment by NilsEnevoldsen** [comment]
LGTM. I corrected a typo and made a few minor style tweaks that you can review.

**Comment by NilsEnevoldsen** [comment]
Oh, I did not subsequently regenerate the pdf.

**Comment by vincentarelbundock** [comment]
Thanks both!

I'm not exactly sure how the process is supposed to work, but I made a submission (basically, just entered the `countrycode` repo URL in their web form. I also added paper.md and paper.bib to the main countrycode repo.

I think we only need to wait now, but I'll check in with the JOSS in a few weeks if I don't see any movement.
